### ISSUE TITLE
議事録

### ISSUE THREAD

**Issue by k-kohey** [k-kohey/Mentoring#4]
## 2022/01/16

- [x] 予約方法の相談
  - Googleカレンダーで予約する。
- [x] 連絡方法の相談
  - Mentaの方でやる。
- [x] 質問の貯め方
- [x] 質疑応答
- [x] 情報共有

**Comment by KenKato-Dev** [comment]
テスト

**Comment by k-kohey** [comment]
2022/01/27

- ほげほげ

**Comment by KenKato-Dev** [comment]
1/25
質問です、Cellに入力内容を入れて実際にシミュを行おうとしたのですが下記のエラーが出ました
The tablecell outlet from the ViewController to the UIView is invalid. Outlets cannot be connected to repeating content.
outletは繰り返しの内容には接続できないと書いておりますがoutletとは何を指しているのでしょうか？
また上記解決内容を調べるとCell専用のVIewを用意する方法を見つけましたがこの方法が正しいのでしょうか？

**Comment by k-kohey** [comment]
@KenKato-Dev 

面談前ですが情報を小出しします．


> outletとは何を指しているのでしょうか？

`@IBOutlet ...`と定義されたUIの事を指しています．
こちらがドキュメントになります．

https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Outlets/Outlets.html

> また上記解決内容を調べるとCell専用のVIewを用意する方法を見つけましたがこの方法が正しいのでしょうか？

はい．推奨します．
[UITableViewCell](https://developer.apple.com/documentation/uikit/uitableviewcell)を継承した新しいクラスを作ってみてください．

**Comment by KenKato-Dev** [comment]
## 1/30
面談ありがとうございました、今日だけで分からないところが判明したので復習しておきます。
下記に新たに出たエラーを記載しておきます。このエラーは入力保存後、再度入力し保存をタップすると発生します。
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
そもそもOutlet接続がちゃんとできていないから中身がカラ扱いになったのかと思いましたがcell内のテキストは両方とも接続されております。
またcellそのものをOutlet接続および変数宣言した時の残骸が残っていたので消しましたが状態変わりません。
引き続き取り組みたいと思います。

**Comment by k-kohey** [comment]
@KenKato-Dev 
[このサイト](https://teratail.com/questions/100161)の回答は間違っている可能性が高いです．
`@IBOutlet`と付いているのはStoryboard（あるいはxib）を使ってUIを構築していることを示しています．
この`@IBOutlet`という宣言を使うことによって，Storyboard（あるいはxib）からUIの位置情報や大きさをiOSが判断して描画します．
このときUIの変数，例えば今回の例だと`LeftCellLabel`，に対して値の代入もiOSが自動で行ってくれます．
この自動で代入される変数に位置情報や大きさが詰まっているので（厳密にはAutoLayoutという仕組み）Storyboardで指定した画面のとおりに描画され，という流れです．

一方で`LeftCellLabel = UILabel()`というふうに宣言すると，その位置情報や大きさが詰まった変数の代入が行われません．
なので，何も表示されない現象が起こっているのだと考えられます．

問題はStoryboardとSwiftファイルの連携にあるのだと思われます．
`@IBOutlet`で宣言した変数がnilになっているのはその可能性が高いです．
`tableView.register(UINib(nibName: "CellのUIを設定しているファイル名", bundle: nil), forCellReuseIdentifier: "cell")`のようにするとどうなるでしょうか??

詳細はまた面談時にフォローします．

**Comment by KenKato-Dev** [comment]
## 2/6
GitHubの件ですがScopeを選ぶところを見落として少し手間取りましたが無事トークンを入れられました、ありがとうございます。
引き続きインデックスバーの表示に取り組みます。

**Comment by KenKato-Dev** [comment]
## 2/13
現在cell内にUIbuttonを入れてチェックボックスの実装に取り組んでおり質問があります。
cell内のUIbutton用にプロトコルをUIbuttonとしたクラスを用意してカスタムクラスに設定しましたがボタンを選んでもAssistantsにこのサブクラスを選択できません。
無理矢理Outlet接続できるとは思うのですが、選択できないということは定石ではないということでしょうか？
考えとしてはUI ImageがsystemNameのsquareとsquare.checkmarkで切り替わるようにしようと考えております。

**Comment by k-kohey** [comment]
下記の手順で試してみてください。

1. Storyboardにて`CheckBox`の実装を反映させたいButtonをクリック
2. 右側に表示されているメニューの中からCustom Classがあるタブ（左から４つ目のタブ）を開く。
3. Classに`CheckBox`と入力

また、CheckBoxはCheckBoxButtonに改名することを推奨します。

**Comment by KenKato-Dev** [comment]
## 2/21
早速toggleで□と☑︎が入れ替わるようにしました。
またボタンがどのように動作しているか確認するため下記のように記載しました。
func toggle(){
        isCheck.toggle()
    }
@objc func selectBox(_ sender: UIButton) {
        box.toggle()
        var boxClick = 0
        if box.isCheck == false {
            box.setImage(box.emptyBox, for: .normal)
            boxClick += 1
            print("□です")
        }else{
            box.setImage(box.checkedBox, for: .normal)
            boxClick += 1
            print("☑︎です")
        }
        print("\(box.tag+1)番目のボタンが\(boxClick)回押されました")
    }
結果は解説いただいた通りボタンはここに動き、また配列でなく独立したボタンのためどのボタンも1番目のボタンとなり、
Toggle（）のためだと思うのですがboxClickは何度押しても1回押されましたと表示されました。
・次の課題は①.ishiddenからボタンが現れるようにする動作、②.filterなどのメソッドでチェックされていないもののみがfoodsに入るようにすることだと考えてます。
前回前々回いただいた資料で復習や勉強しつつ上記課題を進めたいと思います。

**Comment by KenKato-Dev** [comment]
## 2/25
面談ありがとうございました。早速FizzBuzz問題やってみました。余剰演算子を知らなかったのでそこだけ確認し下記の通り描いてみました。

var number = 0
func FizzBuzzChecker(number:Int){
    if number % 3 == 0 && number % 5 == 0{
        print("FizzBuzz")
    }else if number % 3 == 0{
        print("Fizz")
    }else if number % 5 == 0{
        print("Buzz")
    }else{
        print("FizzBuzzじゃない")
    }
}

これでFizzBuzzChecker関数に任意の数字を入れることで動作を確認できました。
ただし0を入れるとFizzBuzzになりますがこれは間違いでしょうか？

**Comment by k-kohey** [comment]
伝え忘れていましたが入力値は自然数なので0の考慮はなくてOKです！
キモとなる部分はバッチリだと思います👌
一応，以下に回答を置いておきます．

```swift

func fizzBuzzChecker(number:Int) {
  if number % 15 == 0 {
    print("FizzBuzz")
  } else if number % 3 == 0 {
    print("Fizz")
  } else if number % 5 == 0 {
    print("Buzz")
  } else {
    print(number)
  }
}



```

**Comment by k-kohey** [comment]
論理積と論理和のの練習も取り組んでいいと思ったのでもう一問共有しておきます！
寝る前とかにでも考えてみてください🙌

問）

善人は青信号のときに横断歩道を渡り，赤信号の時に渡らない．
悪人は青信号のときに横断歩道を渡り，赤信号の時にも渡る．

ある関数に，善人か悪人かを示す変数と青信号か赤信号化を示す変数が与えられた時に，横断歩道を渡るかどうかを出力したい．
下記の2つのコードはその実装をそれぞれ別の方法で行っている．
コード中の虫食いになっている論理式Aと論理式Bを答えよ．
ただし，論理式Aには論理和`||`が，論理式Bには論理積`&&`が含まれる必要がある．

```swift
enum Signal {
    case blue
    case red
}

func resolveA(isGoodPeople: Bool, signal: Signal) {
    if 論理式A {
        print("信号を渡る")
    } else {
        print("信号を渡らない")
    }
}

func resolveB(isGoodPeople: Bool, signal: Signal) {
    if 論理式B {
        print("信号を渡る")
    } else {
        print("信号を渡らない")
    }
}

```

**Comment by KenKato-Dev** [comment]
> 伝え忘れていましたが入力値は自然数なので0の考慮はなくてOKです！ キモとなる部分はバッチリだと思います👌 （キモ：ちゃんとロジックが組めるか） 一応，以下に回答を置いておきます．
> 
> ```swift
> func fizzBuzzChecker(number:Int) {
>   if number % 15 == 0 {
>     print("FizzBuzz")
>   } else if number % 3 == 0 {
>     print("Fizz")
>   } else if number % 5 == 0 {
>     print("Buzz")
>   } else {
>     print(number)
>   }
> }
> ```

回答ありがとうございます、確かに割り切れたらいいので2数の最小公倍数でいいですね

**Comment by KenKato-Dev** [comment]
> 論理積，論理和，論理否定の練習も取り組んでいいと思ったのでもう一問共有しておきます！ 寝る前とかにでも考えてみてください🙌
> 
> 問）
> 
> 善人は青信号のときに横断歩道を渡り，赤信号の時に渡らない． 悪人は青信号のときに横断歩道を渡り，赤信号の時にも渡る．
> 
> ある関数に，善人か悪人かを示す変数と青信号か赤信号化を示す変数が与えられた時に，横断歩道を渡るかどうかを出力したい． 下記の2つの関数`resolveA`と`resolveB`はその実装をそれぞれ別の方法で行っている． コード中の虫食いになっている論理式Aと論理式Bを答えよ． ただし，論理式Aには論理和`||`が，論理式Bには論理積`&&`が含まれる必要がある．
> 
> ```swift
> enum Signal {
>     case blue
>     case red
> }
> 
> func resolveA(isGoodPeople: Bool, signal: Signal) {
>     if 論理式A {
>         print("信号を渡る")
>     } else {
>         print("信号を渡らない")
>     }
> }
> 
> func resolveB(isGoodPeople: Bool, signal: Signal) {
>     if 論理式B {
>         print("信号を渡る")
>     } else {
>         print("信号を渡らない")
>     }
> }
> ```

下記の通り考えてみましたが2種類目が思い浮かびません


num Signal{
    case blue
    case red
}

func resolveA(isGoodPeople: Bool, signal:Signal){
    if isGoodPeople == false || isGoodPeople == true && signal == .blue {
        print("信号を渡る")
    }else{
        print("信号を渡らない")
    }
}
resolveA(isGoodPeople: true, signal: .red)

引き続き考えてみたいと思います

**Comment by k-kohey** [comment]
いいですね！

では，論理否定`!`と論理積`&&`だけを使って表現するとどうでしょうか？？

**Comment by KenKato-Dev** [comment]
> いいですね！
> 
> では，論理否定`!`と論理積`&&`だけを使って表現するとどうでしょうか？？

## 3/5
考えていますが、その演算子だけ使った表現が思いつかないです。
引き続き考えてみたいと思います。

**Comment by k-kohey** [comment]
<img width="591" alt="スクリーンショット 2022-03-06 21 11 58" src="https://user-images.githubusercontent.com/26789330/156922538-b6e9bac2-f271-4f4d-a172-28c99f7015ce.png">

**Comment by KenKato-Dev** [comment]
> <img alt="スクリーンショット 2022-03-06 21 11 58" width="591" src="https://user-images.githubusercontent.com/26789330/156922538-b6e9bac2-f271-4f4d-a172-28c99f7015ce.png">

図の共有ありがとうございます、意識しながら書くよう心がけます

**Comment by KenKato-Dev** [comment]
## 2022/03/06

クロージャdidTapCheckBoxでIDを取得できるようになったので配列checkedFoodsIDにappendさせるようにしてfor inで配列からひとつずつ取り出しremoveFoodsを実行したところ一部うまくいきました。
現在実行を削除ボタンの@objc func removeFuncに組み込んでおり、任意の列を削除後再度ゴミ箱ボタンをタップして□を表示させるとその消した項の一つ前の項が☑︎の状態になっており、☑︎から□に戻して削除ボタンを押すと戻した項目が消えます。
この不具合に取り除けば管理アプリの下地は整うので頑張りたいと思います。

**Comment by k-kohey** [comment]
```swift
var dictionary: [String: Food] = [:]
dictionary["hogehoge"] = food1
print(dictionary["hogehoge"]) // food1
dictionary["hogehoge"] = food2
print(dictionary["hogehoge"]) // food2

var checkedFood: [String: Bool] = [:]
checkedFood["UUID-hogehoge...."] = isCheked

let cell = table.dequeue(...)
cell.isCheckd = checkedFood[food.id]
```

**Comment by KenKato-Dev** [comment]
## 2022/03/14
アドバイスされたUUIDを使わずにKeyを取得する方法で下記の通り実装することができました。
```swift
@objc func removeFunc(_ sender: UIButton){
        var FoodDictionaryKeys = checkedFoodDictionary.keys
        isShow.toggle()
        removeButton.appearanceChange(push: isShow)
        for dictionaryKey in FoodDictionaryKeys{
            foods.removeFoods(key: dictionaryKey)
            checkedFoodDictionary = [:]
        }
        table.reloadData()
        }
```
現在の課題は一度でもタップしをするとその時点でdictionaryに入ってしまいチェックを外してもそのまま残ってしまうことで削除ボタンを押すと削除されてしまうことです。引き続き実装ではこの課題解決に取り組みたいと思います。

**Comment by KenKato-Dev** [comment]
##2022/03/23
ゆめみさんの課題に取り組んでいたところ以下のエラーが突然発生しました。

Showing Recent Messages
Could not find or use auto-linked library 'XCTestSwiftSupport'
Could not find or use auto-linked framework 'XCTest'
Undefined symbol: __swift_FORCE_LOAD_$_XCTestSwiftSupport

調べるとVar11.4の頃の回答でXcodeのVerによるエラーのように書いていたのですがこういった場合はどうすべきでしょうか？

**Comment by k-kohey** [comment]
```json
{
  "name": "Taro",
  "Area": "Tokyo",
  "age": 15,
  "children": ["Ichiro", "jiro"]
}
```


```swift

let json = """
{ "name": "Taro"} 
"""

```
